---
- name: R1 static config
  hosts: ASW1
  connection: local

  tasks:
    - name: Static route on R1 to R2
      ios_config:
        lines:
           - ip routing
           - ip route 192.168.64.0 255.255.255.252 192.168.1.1
# This playbook can be used for when you add a VLAN with a new network that isn't currently routed.
# Use case TACLAN Router to Switch with new subnet. 

# ---
# - name: R2 static config
#   hosts: student1-rtr2.net-ws.redhatgov.io
#   connection: local

#   tasks:
#     - name: Static route on R2 to R1
#       ios_config:
#         lines:
#           - ip route 172.17.1.0 255.255.255.0 10.0.0.1