---
- hosts: switches
  gather_facts: yes
  connection: local 


  tasks:
  - name: GET CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE CONNECTION
    set_fact:
       connection:
          authorize: yes
          host: "{{ inventory_hostname }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"

  - name: Remove MGMT ACL from VTY
    ios_config:
      provider: "{{ connection }}"
      lines:
        - no access-class ACL_MGMT in
      parents: ['line vty 0 15']

  - name: Remove MGMT ACL from Switches
    ios_config:
      provider: "{{ connection }}"
      lines:
        - no ip access-list extended ACL_MGMT
    

  - name: SHOW VTY ACL
    ios_command:
      provider: "{{ connection }}"
      commands:
        - show run | b line vty 
    register: vtyacl
  - debug: var=vtyacl.stdout_lines
  
  - name: WAIT FOR SSH CONNECTIVITY then SAVE
    wait_for:
      host: "{{ inventory_hostname }}"
      port: 22
      timeout: 10
      msg: SSH Connection failed and must reboot device to regain connectivity

  - name: WRITE ME 2
    ios_command:
      provider: "{{ connection }}"
      commands:
        - wr me 
 
      
      