---
- hosts: switches
  gather_facts: no
  connection: local 

  tasks:
  - name: GET CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE CONNECTION
    set_fact:
       connection:
          authorize: yes
          host: "{{ inventory_hostname }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"

  - name: SHOW VTY ACL
    ios_config:
      provider: "{{ connection }}"
      lines:
        - show run | b line vty 
    register: vtyacl

  - debug: var=vtyacl.stdout_lines




